import type { Metadata } from 'next'

import { ReactNode } from 'react'

import { Header } from '@/components/header/Header'

import '@/styles/index.scss'

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang={'en'}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}
